### ISSUE TITLE
New file popup is broken in Atom One theme

### ISSUE THREAD

**Issue by matmuchrapna** [Trudko/advanced-new-file#14]
![screen shot 2015-04-13 at 03 13 06](https://cloud.githubusercontent.com/assets/559321/7108574/145b23b0-e18b-11e4-9386-729c43a6ded1.png)
I love your plugin, but this thing disappoint me. How can I help you to fix this?

**Comment by Trudko** [comment]
Hey, thanks for kind words and reporting the issue. I was able to reproduce it and if you have an idea where might be a problem I am would love to hear it.

**Comment by matmuchrapna** [comment]
I don’t know where is a problem, but I tried other standard Atom themes, (Atom Dark to be clear) and this theme have no this problem. So maybe Atom One theme have some overridings to advanced-new-file?

**Comment by silentvick** [comment]
I believe the problem is in deprecated styles for modal window: `overlay from-top`. Seems like you don't need these two nowadays. Removing it solves the problem. I'll make a PR.

**Comment by matmuchrapna** [comment]
@Trudko what do you think, about mergin’?

**Comment by Trudko** [comment]
Sure I will check it tomorrow.

**Comment by Trudko** [comment]
Merged and release thanks guys!

**Comment by matmuchrapna** [comment]
![screen shot 2015-04-16 at 15 47 50](https://cloud.githubusercontent.com/assets/559321/7182175/fd2586aa-e44f-11e4-874e-a4e5f9d65dcf.png)
It’s working properly now, Thanks @Trudko @silentvick
