### ISSUE TITLE
Dialog disappears on OS X when temporarily navigating away from panel

### ISSUE THREAD

**Issue by posita** [Trudko/advanced-new-file#17]
There might be times when I bring up the new file dialog, and partially complete a path, but need information from another window. If I navigate away from Atom (e.g., via `cmd-tab`), when I return to Atom, the new file dialog is gone, and I have to start over. It would be nice if the dialog persisted upon my return.

I realize this might be an Atom thing (and not something that can be overcome at the plugin level).

**Comment by vladimirstarkov** [comment]
I think it’s an Atom-related issue, because all other dialog behave the same.

**Comment by posita** [comment]
Feel free to close as a duplicate of atom/atom#1918.
