### ISSUE TITLE
Simplify navigating up directory structure

### ISSUE THREAD

**Issue by lee-dohm** [Trudko/advanced-new-file#2]
One thing I miss from the Emacs implementation of this feature is how easy it was to move *up* the directory tree. An example:

1. You're in a file in `foo/bar/`
1. Press <kbd>Cmd+Alt+N</kbd>, Advanced New File shows `foo/bar/|` (`|` represents the cursor)
1. Press <kbd>Backspace</kbd> once, Advanced New File now shows `foo/|`

If your cursor is after a backslash and you press <kbd>Backspace</kbd>, it deletes one entire directory. Otherwise, it works normally. This makes things *much* faster when working on projects with insanely nested directory structures (like Java projects which sadly some of us still have to work on :cry:).

**Comment by Trudko** [comment]
Hi @lee-dohm , you are first to create issue in my package, you should win something :).

I like your proposal and I would like to ask you  for clarification. By You're in a file in foo/bar/ , do you mean that you have file opened in this folder? If yes do you want to Advanced New File start in this folder rather then root of the project?

Secondly what if I want to rename the bar folder name? If backspace would delete whole name of bar I would have to use arrows and delete to rename the bar.

**Comment by lee-dohm** [comment]
By "you're in a file in `foo/bar/`" I mean that there is a file open in Atom that exists in the directory `foo/bar/` underneath the project directory. 

> If yes do you want to Advanced New File start in this folder rather then root of the project?

Yes, this feature already exists. For example: `foo/bar/baz.md` is open in the main Atom window. If the `advanced-new-file.suggestCurrentFilePath` option is set to `true`, when I press <kbd>Cmd+Alt+N</kbd> the edit box is pre-populated with `foo/bar/|`.

> what if I want to rename the bar folder name?

If you want to change the `bar` folder name and create a new file (like `foo/wubble/baz.md`) then you would do this:

1. File `foo/bar/baz.md` is open in Atom
1. Press <kbd>Cmd+Alt+N</kbd>, Advanced New File shows `foo/bar/|`
1. Press <kbd>Backspace</kbd> once, Advanced New File shows `foo/|`
1. Type new folder and name `wubble/baz.md` and press <kbd>RETURN</kbd>

If you want to change the `bar` folder name and just create a new folder `wubble` then you would do this:

1. File `foo/bar/baz.md` is open in Atom
1. Press <kbd>Cmd+Alt+N</kbd>, Advanced New File shows `foo/bar/|`
1. Press <kbd>Backspace</kbd> once, Advanced New File shows `foo/|`
1. Type new folder name followed by directory separator `wubble/` and press <kbd>RETURN</kbd>

If in the *very rare* case you want to create a new directory with a very similar name to the one that already exists like `barista` then you would do this:

1. File `foo/bar/baz.md` is open in Atom
1. Press <kbd>Cmd+Alt+N</kbd>, Advanced New File shows `foo/bar/|`
1. Press <kbd>LEFT</kbd> once, Advanced New File shows `foo/bar|/`
1. Type the rest of the folder name `ista` and press <kbd>RETURN</kbd>

**or** you could just press <kbd>Backspace</kbd> like normal, type `barista/` and press <kbd>RETURN</kbd>.

But believe me, the last example is really quite rare in comparison to the first two scenarios. I think it is quite reasonable to optimize the common case at the expense of the uncommon one.

**Comment by Trudko** [comment]
@lee-dohm I think I understand it and I do like it so I will take a look at it. Can't promise you date because I want to focus first on removing deprecated code and I want to take closer look at isuess in old package which weren't addressed for several weeks.

**Comment by lee-dohm** [comment]
Thanks for taking a look! :grinning:

**Comment by Trudko** [comment]
Do you mean something like this? 

![advanced-new-file-lee](https://cloud.githubusercontent.com/assets/3289225/5903711/8d20729e-a583-11e4-8114-07e01af0c2ae.gif)

**Comment by lee-dohm** [comment]
Yes, that's it :+1:

**Comment by Trudko** [comment]
Ok because this is not possible :D I should release it at the end of this week, cause I can work on it mostly on weekends.

**Comment by lee-dohm** [comment]
Thanks a bunch for working on it :grinning:

**Comment by Trudko** [comment]
@lee-dohm any tips how to disable backspace keypress?

**Comment by lee-dohm** [comment]
In my [bug-report package](https://atom.io/packages/bug-report), I just added commands for `core:focus-next` and `core:confirm` to the controls I wanted to handle those commands:

https://github.com/lee-dohm/bug-report/blob/master/lib/panel-view.coffee#L86-L90

I assume you could do the same thing with `core:backspace`.
