### ISSUE TITLE
Can't create a folder without specifying a file

### ISSUE THREAD

**Issue by Dargaard** [Trudko/advanced-new-file#37]
I can't figure out how to create just a folder. Typing newfolder\ or newfolder/ creates a file called newfolder once it's saved, not a new directory like it does in Sublime.

**Comment by vynogradskyi** [comment]
Same issue

**Comment by Trudko** [comment]
Hi guys please take a look at https://github.com/Osmose/advanced-open-file, it replaces this project which I can't maintain anymore. Thank you for understanding :)

**Comment by iamstarkov** [comment]
You probably should comment the same in all issues you closed today

**Comment by Trudko** [comment]
Yeah I started , but there were too many issues and I added comment to readme.
