### ISSUE TITLE
Can't create multiple files just like the demo gif did

### ISSUE THREAD

**Issue by coolzilj** [Trudko/advanced-new-file#38]
I can't create multiple files using comma just like the demo gif did.
And I miss something? 
Atom Version 0.207.0 (0.207.0)

**Comment by Trudko** [comment]
Hi what do you mean you can't ? What happens instead?

**Comment by coolzilj** [comment]
Let's say I type `main.css, main.html` after invoking, only an empty `main.css`(the first one) tab shows up, instead of two tabs.

**Comment by Trudko** [comment]
Hi :) please  take a look at https://github.com/Osmose/advanced-open-file, it replaces this project which I can't maintain anymore. Thank you for understanding :)
