### ISSUE TITLE
Can't install v0.2.0

### ISSUE THREAD

**Issue by lee-dohm** [Trudko/advanced-new-file#4]
I assume because of the new `engines` value. Even when I completely uninstall `advanced-new-file` and install again, the v0.1.0 version is installed.

**Comment by Trudko** [comment]
@lee-dohm do you have problem with 0.2.1?

**Comment by lee-dohm** [comment]
Yeah, still doesn't install on a `master` branch compiled version. I think that's what it is, the version checking says that Atom is a pre-release version so unless you specify the exact version it won't install.

**Comment by Trudko** [comment]
@lee-dohm you mean if I don't specify exact version of Atom in package.json?

**Comment by lee-dohm** [comment]
I forget where I saw it now, but basically since I build from `master` my Atom version number is `v0.178.0-deadbeef` (or some other hash). Because of the hash at the end, Node considers this a "pre-release" version. If you say you are compatible with `>=v0.5.0`, Node only matches that with *released* versions greater than or equal to v0.5.0, but if you say that you're compatible with `>=v0.5.0-alpha1` then it'll accept v0.5.0-beta5 but not v0.6.0-beta9. Or something like that ... like I say, I can't find the reference now :cry:

**Comment by lee-dohm** [comment]
Orrrr I could be completely wrong and you got bit by atom/atom#5417. It looks like it should be space-separated ... not comma-separated.

**Comment by Trudko** [comment]
I see :) I will take a look at https://github.com/Trudko/advanced-new-file/issues/5 and will release this with it during the weekend.

**Comment by Trudko** [comment]
I've pushed new version please try that one

**Comment by lee-dohm** [comment]
That one worked, thanks!
