### ISSUE TITLE
Use the fuzzy finder

### ISSUE THREAD

**Issue by AntoineBoulanger** [Trudko/advanced-new-file#41]
Would it be possible to use the [atom fuzzy finder](https://github.com/atom/fuzzy-finder) to find the sub folder you want to create your file in, without having to type the whole path/to/file.txt ? Exemple: https://github.com/noklesta/SublimeQuickFileCreator this plugin did it for Sublime Text.

**Comment by Trudko** [comment]
Hi :) please  take a look at https://github.com/Osmose/advanced-open-file, it replaces this project which I can't maintain anymore. Thank you for understanding :)
