### ISSUE TITLE
Create new file relative to the current file

### ISSUE THREAD

**Issue by svenax** [Trudko/advanced-new-file#45]
In a similar package for Sublime Text 3, it is possible to create new files relative to the currently opened and focused file by prefixing the path with **:**. When using path completion, this changes to a full project relative path. This feature is convenient when creating new files in a nested folder structure.

**Comment by Trudko** [comment]
Hi :) please take a look at https://github.com/Osmose/advanced-open-file, it replaces this project which I can't maintain anymore. Thank you for understanding :)

**Comment by iamstarkov** [comment]
@Trudko thank you for all the time and efforts you spent on this project, I loved it and it saved me a tons of hours. thank you

**Comment by Trudko** [comment]
Thank you for kinds words! I sincerely appreciated it.
