### ISSUE TITLE
Opens new window with new file

### ISSUE THREAD

**Issue by raddevon** [Trudko/advanced-new-file#5]
When I create a new file with advanced-new-file, it opens a new window with the file. Is it possible to have the new file created in the current window?

**Comment by raddevon** [comment]
It might be helpful if I tell you exactly what I'm running. :smile:

I'm on OSX 10.10.1 with Atom 0.177.0 and advanced-new-file 0.2.1. I've bound the command to Cmd-N since I want to replace the default new file behavior with it, but it seems to do the same thing if I use the default keybinding.

**Comment by Trudko** [comment]
Hi @raddevon :) this is bit tricky and I've posted issue to atom about that. I do use atom.open functions which has newWindow settings and I set it to false, but sometimes it opens in new window. Will take a closer look at it this weekend :)

**Comment by raddevon** [comment]
Thanks for the reply, @Trudko. I dug a bit deeper and found the `newWindow` option wasn't getting into the `ipc.send` call. Pretty sure that's because the call down [on line 158](https://github.com/Trudko/advanced-new-file/blob/master/lib/advanced-new-file-view.coffee#L158) is passing two arguments to `atom.open` instead of passing the options object.

However, even after explicitly wrapping the options in curly braces, it still opens in a new window. I can verify that the whole object is getting through now, but it doesn't seem to help.

Here's my line 158:

    atom.open {pathsToOpen: [pathToCreate], newWindow: false}

**Comment by Trudko** [comment]
Thanks for taking your time, yeah I need to take a closer look at atom.open during the weekend it is bit confusing imho at least documentation is.

**Comment by Trudko** [comment]
@raddevon I've published new version where I used atom.workspace.open instead of atom.open. For me it seems to work. Please try it and let me know.

**Comment by raddevon** [comment]
@Trudko That seems to be working perfectly. Thanks for the fix!

**Comment by Trudko** [comment]
@raddevon thanks for creating an issue and the help!
