### ISSUE TITLE
Have u reslove this problem?

### ISSUE THREAD

**Issue by yksalun** [Trudko/advanced-new-file#50]
Hi，i saw this problem in https://github.com/atom/fuzzy-finder/issues/76 that u ask，and i hava this problem too，have u reslove this problem？if u did，can u tell me how? thx

**Comment by iamstarkov** [comment]
use [advanced-open-file](https://atom.io/packages/advanced-open-file) instead, it replaces this project which @Trudko can't maintain anymore. Thank you for understanding :)

**Comment by yksalun** [comment]
awsome! thank u

**Comment by iamstarkov** [comment]
would you mind to close issue, then? =)
