### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by jelmerdemaat** [Trudko/advanced-new-file#6]
Just an automatic issue to notify about deprecated methods:

atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (C:\Users\jelmaa\AppData\Local\atom\app-0.177.0\resources\app\src\atom.js:54:11)
AdvancedFileView.attach (C:\Users\jelmaa\.atom\packages\advanced-new-file\lib\advanced-new-file-view.coffee:180:9)
```

**Comment by Trudko** [comment]
@jelmerdemaat Thank you for the info I am aware of the issue I will take a look at it during this week 
:)

**Comment by jelmerdemaat** [comment]
:+1:

**Comment by Trudko** [comment]
@jelmerdemaat this should be resolved so I will close it if you agree.

**Comment by jelmerdemaat** [comment]
Yep, no longer seeing this message!

**Comment by Trudko** [comment]
Great :) closing the issue.
